# Mod
version = 26.3.0.0
mod_id = nolittering
mod_name = No Littering
mod_author = BlayTheNinth
credits = BlayTheNinth
group = net.blay09.mods
description=Removes Leaf Litter from world generation and provides alternative means of obtaining it.
homepage=https://mods.twelveiterations.com/mc/no-littering
sources=https://github.com/TwelveIterations/NoLittering
issues=https://github.com/TwelveIterations/NoLittering/issues
discord = https://discord.gg/VAfZ2Nau6j
license=All Rights Reserved

# Publishing
curseforge_project_id = 1220046
curseforge_environments = Server
modrinth_project_id = J0lH25Dm
maven_releases = https://maven.twelveiterations.com/repository/maven-releases/
maven_snapshots = https://maven.twelveiterations.com/repository/maven-snapshots/

# Build
java_version = 25
neoforge_snapshot_url =
include_fabric=true
include_neoforge=false
include_forge=false

# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
