modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="${issues}"
[[mods]]
modId="nolittering"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage}"
iconFile="nolittering.png"
credits="${credits}"
authors="${mod_author}"
description='''${description}'''
[[mixins]]
config = "nolittering.mixins.json"
[[mixins]]
config = "nolittering.neoforge.mixins.json"
[[dependencies.nolittering]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.nolittering]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.nolittering]]
modId="balm"
type="required"
versionRange="[${balm_version},)"
ordering="NONE"
side="BOTH"
